name = "Helloworld"
uuid = "6de1a419-4ac9-46d8-b5e8-1146135d8078"
authors = ["Keishi Sando <nobuta05@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
